---
- name: Inlcude tasks to configure SQL support
  ansible.builtin.include_tasks: configure_sql_support.yml
  when: postfix_sql_backend in ['mysql', 'pgsql']

- name: Place main.cf
  ansible.builtin.template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: '0644'
  notify: "postfix config changed"

- name: Place master.cf
  ansible.builtin.template:
    src: master.cf.j2
    dest: /etc/postfix/master.cf
    owner: root
    group: root
    mode: '0644'
  notify: "postfix config changed"
