---
- name: Install postfix
  ansible.builtin.package:
    name: "postfix"
    state: present

- name: Add MySQL map support package to extra packages
  ansible.builtin.set_fact:
    postfix_extra_packages: "{{ postfix_extra_packages + ['postfix-mysql'] }}"
  when: postfix_sql_backend == "mysql"

- name: Add PostgreSQL map support package to extra packages
  ansible.builtin.set_fact:
    postfix_extra_packages: "{{ postfix_extra_packages + ['postfix-pgsql'] }}"
  when: postfix_sql_backend == "pgsql"

- name: Add SQLite map support package to extra packages
  ansible.builtin.set_fact:
    postfix_extra_packages: "{{ postfix_extra_packages + ['postfix-sqlite'] }}"
  when: postfix_sql_backend == "sqlite"

- name: Install extra packages
  ansible.builtin.package:
    name: "{{ postfix_extra_packages }}"
    state: present
