---
- name: Inlcude tasks to install postfix
  include_tasks: install.yml

- name: Inlcude tasks to configure postfix
  include_tasks: configure.yml

- name: Enable and start postfix service
  service:
    name: postfix
    state: started
    enabled: true
