---
- name: Inlcude tasks to install postfix
  ansible.builtin.include_tasks: install.yml

- name: Inlcude tasks to configure postfix
  ansible.builtin.include_tasks: configure.yml

- name: Enable and start postfix service
  ansible.builtin.service:
    name: postfix
    state: started
    enabled: true
