---
- name: Converge
  hosts: all
  become: true
  gather_facts: true

  pre_tasks:
    - name: Include variables for test of RHEL based OS
      ansible.builtin.include_vars:
        file: osfamily_redhat.yml
      when: ansible_os_family == "RedHat"

    - name: Include variables for test of Debian based OS
      ansible.builtin.include_vars:
        file: osfamily_debian.yml
      when: ansible_os_family == "Debian"

  roles:
    - role: ansible_role_postfix
