---
- name: Converge
  hosts: all
  become: true
  gather_facts: true

  vars:
    postfix_configuration:
      "default (ipv4 only)":
        compatibility_level: 2
        queue_directory: /var/spool/postfix
        command_directory: /usr/sbin
        daemon_directory: /usr/libexec/postfix
        data_directory: /var/lib/postfix
        mail_owner: postfix
        inet_interfaces: localhost
        inet_protocols: ipv4
        mydestination: $myhostname, localhost.$mydomain, localhost
        unknown_local_recipient_reject_code: 550
        alias_maps: "hash:/etc/aliases"
        alias_database: "hash:/etc/aliases"
        debug_peer_level: 2
        debugger_command: "PATH=/bin:/usr/bin:/usr/local/bin:/usr/X11R6/bin ; ddd $daemon_directory/$process_name $process_id & sleep 5"
        sendmail_path: /usr/sbin/sendmail.postfix
        newaliases_path: /usr/bin/newaliases.postfix
        mailq_path: /usr/bin/mailq.postfix
        setgid_group: postdrop
        html_directory: "no"
        manpage_directory: /usr/share/man
        sample_directory: /usr/share/doc/postfix/samples
        readme_directory: /usr/share/doc/postfix/README_FILES
        smtpd_tls_cert_file: /etc/pki/tls/certs/postfix.pem
        smtpd_tls_key_file: /etc/pki/tls/private/postfix.key
        smtpd_tls_security_level: may
        smtp_tls_CApath: /etc/pki/tls/certs
        smtp_tls_CAfile: /etc/pki/tls/certs/ca-bundle.crt
        smtp_tls_security_level: may
        meta_directory: /etc/postfix
        shlib_directory: /usr/lib64/postfix

  roles:
    - role: ansible_role_postfix
