---
name: Role testing with Molecule

on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: molecule
        uses: robertdebock/molecule-action@2.6.16
        with:
          command: lint
  test:
    needs:
      - lint
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        image:
          - docker-centos8-ansible
          - docker-rockylinux9-ansible
          - docker-rockylinux10-ansible
          - docker-ubuntu2204-ansible
          - docker-ubuntu2404-ansible
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: molecule
        uses: robertdebock/molecule-action@2.6.16
        with:
          namespace: geerlingguy
          image: "${{ matrix.image }}"
          options: parallel
          tag: latest
